CREATE TABLE DEMO_QUEUE_TABLE
   (	Q_NAME VARCHAR2(128),
	MSGID RAW(16),
	CORRID VARCHAR2(128),
	PRIORITY NUMBER,
	STATE NUMBER,
	DELAY TIMESTAMP (6),
	EXPIRATION NUMBER,
	TIME_MANAGER_INFO TIMESTAMP (6),
	LOCAL_ORDER_NO NUMBER,
	CHAIN_NO NUMBER,
	CSCN NUMBER,
	DSCN NUMBER,
	ENQ_TIME TIMESTAMP (6),
	ENQ_UID VARCHAR2(128),
	ENQ_TID VARCHAR2(30),
	DEQ_TIME TIMESTAMP (6),
	DEQ_UID VARCHAR2(128),
	DEQ_TID VARCHAR2(30),
	RETRY_COUNT NUMBER,
	EXCEPTION_QSCHEMA VARCHAR2(128),
	EXCEPTION_QUEUE VARCHAR2(128),
	STEP_NO NUMBER,
	RECIPIENT_KEY NUMBER,
	DEQUEUE_MSGID RAW(16),
	SENDER_NAME VARCHAR2(128),
	SENDER_ADDRESS VARCHAR2(1024),
	SENDER_PROTOCOL NUMBER,
	USER_DATA SYS.AQ$_JMS_TEXT_MESSAGE ,
	USER_PROP SYS.ANYDATA ,
	 PRIMARY KEY (MSGID)
  USING INDEX  ENABLE
   ) USAGE QUEUE
 VARRAY USER_DATA.HEADER.PROPERTIES STORE AS SECUREFILE LOB ;
CREATE INDEX AQ$_DEMO_QUEUE_TABLE_I ON DEMO_QUEUE_TABLE (Q_NAME, STATE, ENQ_TIME, STEP_NO, CHAIN_NO, LOCAL_ORDER_NO)
  ;
CREATE INDEX AQ$_DEMO_QUEUE_TABLE_T ON DEMO_QUEUE_TABLE (TIME_MANAGER_INFO)
  ;

